name: duration
description: Utilities to make working with 'Duration's easier. Formats duration in human readable form and also parses duration in human readable form to Dart's Duration.
version: 3.0.6
homepage: https://github.com/desktop-dart/duration

documentation:

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.16.7
  pedantic: ^1.11.0
