name: duration
description: Utilities to make working with 'Duration's easier. Formats duration in human readable form and also parses duration in human readable form to Dart's Duration.
version: 2.0.9
homepage: https://github.com/desktop-dart/duration
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.3.0
  pedantic:
